config/routes.rb
Rails.application.routes.draw do

  resources :vendors
  get 'ajax_calls/find_sub_categories'
  get 'ajax_calls/category_products'
  get 'ajax_calls/check_email_taken'
  get 'dashboard/home'

  get 'dashboard/categories'

  get 'dashboard/products'

  get 'dashboard/users'

  get 'dashboard/reviews'

  get 'dashboard/orders'

  devise_for :users
  resources :products
  get 'home/index'
  get 'home/about'
  get 'home/contact'

  resources :categories
  resources :sub_categories
  resources :cart_line_items
  resources :reviews
  resources :wish_lists
  resources :orders
  resources :addresses
  root 'products#index'

end

app/models/address.rb
class Address < ActiveRecord::Base

	belongs_to :user
	has_many :orders
	belongs_to :cart_line_item
	validates_presence_of :user_id, :street, :pin, :city, :landmark
	validates_numericality_of :user_id, :pin
	validates_length_of :pin, is:6
end

app/models/bank_customer.rb
class BankCustomer < ActiveRecord::Base

	validates_presence_of :name, :acc_no, :balance
	validates_numericality_of :balance, greater_than_or_equal_to: 0
	validates_uniqueness_of :acc_no

	def transaction(amount,code)
		if code == 0 
			# if self.balance - amount < 0 
			# 	puts "Insufficient funds"
			# else
				self.balance = self.balance - amount
				self.update_attributes(balance: self.balance)
			# end
		else
			self.balance += 1
			self.update_attributes(balance: self.balance)
		end
	end
end

app/models/cart_line_item.rb
class CartLineItem < ActiveRecord::Base
	belongs_to :user
	belongs_to :product
	has_many :addresses

	validates_presence_of :user_id, :product_id, :quantity
	validates_numericality_of :user_id, :product_id
	validates_numericality_of :quantity, within:1..10

	# instance method / object method
	def save_or_update
		# binding.pry
		line_item = CartLineItem.find_by(user_id: self.user_id, product_id: self.product_id)
		# binding.pry
		if line_item.nil?
			self.save
			# binding.pry
		else
			line_item.update_attributes(quantity: line_item.quantity + self.quantity)
			# binding.pry
		end
		return true
	end

end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :products
    has_many :sub_categories
	validates_presence_of :name
	validates_uniqueness_of :name
end

app/models/order.rb
class Order < ActiveRecord::Base
	has_many :order_line_items
	belongs_to :user
	belongs_to :address
	validates_presence_of :user_id, :order_number, :order_date

	# callback   # argument (method call)
	after_create :copy_cart_line_items_to_order_line_items
	after_create :empty_cart_line_items
	after_create :calculate_total

	def copy_cart_line_items_to_order_line_items
		user = self.user
		user.cart_line_items.each do |line_item|
			order_line_item = OrderLineItem.new
			order_line_item.product_id = line_item.product_id
			order_line_item.quantity = line_item.quantity
			order_line_item.price = line_item.product.price
			order_line_item.total = order_line_item.quantity * line_item.product.price
			order_line_item.order_id = self.id
			order_line_item.save
		end
	end

	def empty_cart_line_items
		user = self.user
		CartLineItem.delete(user.cart_line_items.pluck(:id))
	end

	def calculate_total
		self.update_attributes(total: self.order_line_items.sum(:total))
	end
end

app/models/order_line_item.rb
class OrderLineItem < ActiveRecord::Base

	belongs_to :order
	belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
    belongs_to :category
    belongs_to :sub_category
    has_one :wish_list
    has_many :reviews
    has_many :cart_line_items
    has_many :order_line_items
	validates_presence_of :name, :price, :category_id, :description
	validates_numericality_of :price, :category_id, greater_than_or_equal_to: 1
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :product
	belongs_to :user

	validates_presence_of :body, :rating
	validates_numericality_of :rating
end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
	belongs_to :category
	has_many :products
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :cart_line_items
	has_many :reviews
	has_many :wish_lists
	has_many :orders
	has_many :addresses
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base

	validates_presence_of :name, :email, :mobile
	validates_uniqueness_of :email, :mobile
end

app/models/wish_list.rb
class WishList < ActiveRecord::Base
	belongs_to :product
	belongs_to :user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@categories = Category.order('name DESC')
  end

  def about
  end

  def contact
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/ajax_calls_helper.rb
module AjaxCallsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/home/about.html.erb
<h2>About us</h2>

<a href="/home/index"> Home </a>

<%= link_to "Home (ror)", home_index_path %>
<!-- home_index_path returns a string "/home/index" -->




app/views/home/contact.html.erb
<h2>Contact</h2>

<a href="/home/index"> Home </a>

<%= link_to "Home (ror)", home_index_path %>

app/views/home/index.html.erb
<h2> Welcome to our website</h2>
<!--
<%= %> is embedded ruby tag inside html used for presentation.

<% %> is embedded ruby tag inside html used for evaluation
-->
2 + 2 : <%= 2 + 2 %> <!-- commenting in html -->
<% names = ["ramesh", "suresh", "veeresh", "ganesh"] %>
<ul> <!-- unordered list -->
	<li>Virat</li>
	<li>Dhoni</li>
</ul>

<ol> <!-- ordered list -->
	<li>Apple</li>
	<li>Samsung</li>
	<li>Mi</li>
</ol>

<h3>Listing Names</h3>
<ol>
	<% names.each do |name| %>
	<li><%= name.capitalize %></li>
	<% end %>
</ol>

<% companies = [] %>
<% if companies.empty? %>
<p> Companies not found </p>
<% else %>
<h3>Listing Companies</h3>
<ol>
	<% companies.each do |company| %>
	<li><%= company %></li>
	<% end %>
</ol>
<% end %>


<a href="/home/about"> About</a>
<%= link_to "About(ror)",home_about_path %>
<!-- home_about_path returns a string "/home/about" -->

<a href="/home/contact"> Contact</a>
<%= link_to "Contact(ror)",home_contact_path %>

<h2>Listing Categories</h2>
<ol>
	<% @categories.each do |category| %>
	<li><%= category.name %></li>
	<% end %>
</ol>