config/routes.rb
Rails.application.routes.draw do

  resources :vendors
  get 'ajax_calls/find_sub_categories'
  get 'ajax_calls/category_products'
  get 'ajax_calls/check_email_taken'
  get 'dashboard/home'

  get 'dashboard/categories'

  get 'dashboard/products'

  get 'dashboard/users'

  get 'dashboard/reviews'

  get 'dashboard/orders'

  devise_for :users
  resources :products
  get 'home/index'
  get 'home/about'
  get 'home/contact'

  resources :categories
  resources :sub_categories
  resources :cart_line_items
  resources :reviews
  resources :wish_lists
  resources :orders
  resources :addresses
  root 'products#index'

end

app/models/address.rb
class Address < ActiveRecord::Base

	belongs_to :user
	has_many :orders
	belongs_to :cart_line_item
	validates_presence_of :user_id, :street, :pin, :city, :landmark
	validates_numericality_of :user_id, :pin
	validates_length_of :pin, is:6
end

app/models/bank_customer.rb
class BankCustomer < ActiveRecord::Base

	validates_presence_of :name, :acc_no, :balance
	validates_numericality_of :balance, greater_than_or_equal_to: 0
	validates_uniqueness_of :acc_no

	def transaction(amount,code)
		if code == 0 
			# if self.balance - amount < 0 
			# 	puts "Insufficient funds"
			# else
				self.balance = self.balance - amount
				self.update_attributes(balance: self.balance)
			# end
		else
			self.balance += 1
			self.update_attributes(balance: self.balance)
		end
	end
end

app/models/cart_line_item.rb
class CartLineItem < ActiveRecord::Base
	belongs_to :user
	belongs_to :product
	has_many :addresses

	validates_presence_of :user_id, :product_id, :quantity
	validates_numericality_of :user_id, :product_id
	validates_numericality_of :quantity, within:1..10

	# instance method / object method
	def save_or_update
		# binding.pry
		line_item = CartLineItem.find_by(user_id: self.user_id, product_id: self.product_id)
		# binding.pry
		if line_item.nil?
			self.save
			# binding.pry
		else
			line_item.update_attributes(quantity: line_item.quantity + self.quantity)
			# binding.pry
		end
		return true
	end

end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :products
    has_many :sub_categories
	validates_presence_of :name
	validates_uniqueness_of :name
end

app/models/order.rb
class Order < ActiveRecord::Base
	has_many :order_line_items
	belongs_to :user
	belongs_to :address
	validates_presence_of :user_id, :order_number, :order_date

	# callback   # argument (method call)
	after_create :copy_cart_line_items_to_order_line_items
	after_create :empty_cart_line_items
	after_create :calculate_total

	def copy_cart_line_items_to_order_line_items
		user = self.user
		user.cart_line_items.each do |line_item|
			order_line_item = OrderLineItem.new
			order_line_item.product_id = line_item.product_id
			order_line_item.quantity = line_item.quantity
			order_line_item.price = line_item.product.price
			order_line_item.total = order_line_item.quantity * line_item.product.price
			order_line_item.order_id = self.id
			order_line_item.save
		end
	end

	def empty_cart_line_items
		user = self.user
		CartLineItem.delete(user.cart_line_items.pluck(:id))
	end

	def calculate_total
		self.update_attributes(total: self.order_line_items.sum(:total))
	end
end

app/models/order_line_item.rb
class OrderLineItem < ActiveRecord::Base

	belongs_to :order
	belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
    belongs_to :category
    belongs_to :sub_category
    has_one :wish_list
    has_many :reviews
    has_many :cart_line_items
    has_many :order_line_items
	validates_presence_of :name, :price, :category_id, :description
	validates_numericality_of :price, :category_id, greater_than_or_equal_to: 1
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :product
	belongs_to :user

	validates_presence_of :body, :rating
	validates_numericality_of :rating
end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
	belongs_to :category
	has_many :products
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :cart_line_items
	has_many :reviews
	has_many :wish_lists
	has_many :orders
	has_many :addresses
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base

	validates_presence_of :name, :email, :mobile
	validates_uniqueness_of :email, :mobile
end

app/models/wish_list.rb
class WishList < ActiveRecord::Base
	belongs_to :product
	belongs_to :user
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	before_action :authenticate_user!, except: [:index, :show]
	before_action :check_is_admin, except: [:index, :show]
	   
	def index
		sleep(1)
		if params[:offset]
			@products = Product.offset(params[:offset]).limit(10)
		else
			@products = Product.limit(10)
		end

		respond_to do |format|
			format.html
			format.json {render json: {products: @products}}
		end
	end
	 
	def new 
	  @product = Product.new
	end

	def create
	  @product = Product.new(params[:product].permit(:name, :category_id, :description, :price, :code, :stock, :cod_eligible, :sub_category_id)) 
	   if @product.save
	  	redirect_to products_path, notice: "Successfully created the Product"
	   else
	  	render action: "new"
	   end
	end

	def show
		@product = Product.find(params[:id])
		# @categories = Category.where('id = ?' @product.category_id)
		@category = Category.find(@product.category_id)
		@cart_line_item = CartLineItem.new
		@review = Review.new
	end

	def edit
		@product = Product.find(params[:id])
	end

	def update
		@product = Product.find(params[:id])
		if @product.update_attributes(params[:product].permit(:name, :category_id, :description, :price, :code, :stock, :cod_eligible, :sub_category_id))
			redirect_to product_path(@product.id), notice: "Successfully updated the product"
		else
			render action: "edit"
		end
	end

	def destroy
		@product = Product.find(params[:id])
		@product.destroy
		redirect_to products_path, notice: "Successfully destroyed the product"
	end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/ajax_calls_helper.rb
module AjaxCallsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/helpers/wish_lists_helper.rb
module WishListsHelper
end

app/views/products/edit.html.erb
<h2>Edit Product</h2>

<%= form_for @product do |f| %>
   
   <% if @product.errors.any? %>
      <h3>These errors prohibitted the form from being saved : </h3>
      <ul>
      	<% @product.errors.full_messages.each do |msg| %>
      	   <li><%= msg %></li>
      	<% end %>
      </ul>
    <% end %>

    <label>Code : </label> <br/>
    <%= f.text_field :code,placeholder: "Enter Your Code", autofocus:true %> <br/>

	<label>Name : </label> <br/>
	<%= f.text_field :name, placeholder: "Enter product name", autofocus: true %> <br/>
	<span id= "nameError"> </span>
	<br/>

	<label>Description : </label> <br/>
	<%= f.text_area :description %> <br/>

	<label>Price : </label> <br/>
	<%= f.number_field :price, min: 1, step: 'any' %> <br/>

	<label>Stock : </label> <br/>
	<%= f.text_field :stock %> <br/>
	
	<label>Category : </label> <br/>
	<%= f.collection_select :category_id, Category.all, :id, :name, prompt: "Select Category" %> <br/>

	<label>Sub Category : </label> <br/>
	<%= f.collection_select :sub_category_id, [], :id, :name, prompt: "Select Sub Category" %> <br/>

	<label>COD Eligible : </label> <br/>
	<%= f.check_box :cod_eligible, {checked: true} %> <br/>

	<%= f.submit %> or <%= link_to "back", products_path %>
<% end %>

<script>
	var categoryHandle = document.getElementById('product_category_id');
	var subCategoryHandle = document.getElementById('product_sub_category_id');

	categoryHandle.addEventListener('change', function(){
		subCategoryHandle.innerHTML = "";
		if (categoryHandle.value !== "") {
			var xhr = new XMLHttpRequest();
			xhr.open('GET', "/ajax_calls/find_sub_categories?category_id=" + categoryHandle.value, true);
			xhr.onreadystatechange = function(){
				if (xhr.readyState === 4 && xhr.status === 200) {
					var subCategories = JSON.parse(xhr.responseText);
					subCategories.forEach(function(subCategory){
						var newElement = document.createElement('option');
						var newText = document.createTextNode(subCategory.name);
						newElement.appendChild(newText);
						newElement.setAttribute("value", subCategory.id);
						subCategoryHandle.appendChild(newElement);
					});
				}
			}
			xhr.send();
		}
	}, false);
	// var nameHandle = document.getElementById('product_name');
	// var nameErrorHandle = document.getElementById('nameError');

	// nameHandle.onblur = function(){
	// 	if (nameHandle.value == ""){
	// 		nameErrorHandle.innerHTML = "Can't be blank";
	// 	} else {
	// 		nameErrorHandle.innerHTML = "";
	// 	}
	// };
</script>

app/views/products/index.html.erb
<% if user_signed_in? && current_user.is_admin %>
	<%= link_to "Add Product", new_product_path %>
<% end %>
<div class="row carousel-holder">
    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img class="slide-image" src="images/ucbshoe.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="images/casuals.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="images/tommy.jpg" alt="">
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
</div>

<div class="row">
	<div id="productList">
		<% @products.each do |product| %>
		    <div class="col-sm-4 col-lg-4 col-md-6">
		        <div class="thumbnail">
		            <img src="http://placehold.it/320x150" alt="">
		            <div class="caption">
		                <h4 class="pull-right">$<%= product.price %></h4>
		                <h4><%= link_to product.name, product %></h4>
		                <p>See more snippets like this online store item at <a target="_blank" href="http://www.bootsnipp.com">Bootsnipp - http://bootsnipp.com</a>.</p>
		            </div>
		            <div class="ratings">
		                <p class="pull-right"><%= product.reviews.count %></p>
		                <p>
		                    <span class="glyphicon glyphicon-star"></span>
		                    <span class="glyphicon glyphicon-star"></span>
		                    <span class="glyphicon glyphicon-star"></span>
		                    <span class="glyphicon glyphicon-star"></span>
		                    <span class="glyphicon glyphicon-star"></span>
		                </p>
		            </div>
		        </div>
		    </div>
	    <% end %>
	</div>
</div>


<!-- <a href="/products/new">Add Product</a> -->

<script type="text/template" id="productsTemplate">
	{{#products}}
		<div class="col-sm-4 col-lg-4 col-md-6">
	        <div class="thumbnail">
	            <img src="http://placehold.it/320x150" alt="">
	            <div class="caption">
	                <h4 class="pull-right">$ {{price}} %></h4>
	                <h4>{{name}}</h4>
	                <p>See more snippets like this online store item at <a target="_blank" href="http://www.bootsnipp.com">Bootsnipp - http://bootsnipp.com</a>.</p>
	            </div>
	            <div class="ratings">
	                <p class="pull-right">10Reviews</p>
	                <p>
	                    <span class="glyphicon glyphicon-star"></span>
	                    <span class="glyphicon glyphicon-star"></span>
	                    <span class="glyphicon glyphicon-star"></span>
	                    <span class="glyphicon glyphicon-star"></span>
	                    <span class="glyphicon glyphicon-star"></span>
	                </p>
	            </div>
	        </div>
	    </div>
	{{/products}}
</script>

<script>
	var offset = 10;
	var template = $('#productsTemplate').html()
	$(document).ready(function(){
		$(window).on('scroll',function(){
			if ($(window).scrollTop() > $(document).height() - $(window).height() - 100) {
				var xhr = new XMLHttpRequest();
				xhr.open('GET', '/products.json?offset=' + offset, false);
				xhr.onreadystatechange = function(){
					if(xhr.readyState === 4 && xhr.status === 200){
						var products = JSON.parse(xhr.responseText);
						var newHtml = Mustache.to_html(template, products);
          				$('#productList').append(newHtml);
						offset += 10;
					}
				}
				xhr.send();
			}
		});
	});
</script>












app/views/products/new.html.erb
<h2>Add Product</h2>

<%= form_for @product do |f| %>
   
   	<% if @product.errors.any? %>
      <h3>These errors prohibitted the form from being saved : </h3>
      <ul>
      	<% @product.errors.full_messages.each do |msg| %>
      	   <li><%= msg %></li>
      	<% end %>
      </ul>
    <% end %>
    
    <label>Code : </label> <br/>
    <%= f.text_field :code,placeholder: "Enter Your Code", autofocus:true %> <br/>

	<label>Name : </label> <br/>
	<%= f.text_field :name, placeholder: "Enter product name"%> 
	<span id= "nameError"> </span>
	<br/>

	<label>Description : </label> <br/>
	<%= f.text_area :description %> <br/>

	<label>Price : </label> <br/>
	<%= f.number_field :price, min: 1, step: 'any' %> <br/>
	
	<label>Stock : </label> <br/>
	<%= f.text_field :stock %> <br/>

	<label>Category : </label> <br/>
	<%= f.collection_select :category_id, Category.all, :id, :name, prompt: "Select Category" %>
 	<!-- <span id="productCount"></span> <br/> -->

 	<label>Sub Category : </label> <br/>
	<%= f.collection_select :sub_category_id, [], :id, :name, prompt: "Select Sub Category" %>
 	<!-- <span id="productCount"></span> <br/> -->

	<%= f.check_box :cod_eligible, {checked: true} %>
	<label> : COD Eligible </label> <br/>

	<%= f.submit %> or <%= link_to "back", products_path %>
<% end %>

<script>
	var categoryHandle = document.getElementById('product_category_id');
	var subCategoryHandle = document.getElementById('product_sub_category_id');

	categoryHandle.addEventListener('change', function(){
		subCategoryHandle.innerHTML = "Select subCategory";
		if (categoryHandle.value !== "") {
			var xhr = new XMLHttpRequest();
			xhr.open('GET', '/ajax_calls/find_sub_categories?category_id=' + categoryHandle.value, true);
			xhr.onreadystatechange = function(){
				if (xhr.readyState === 4 && xhr.status === 200) {
					var subCategories = JSON.parse(xhr.responseText);
					subCategories.forEach(function(subCategory){
						var newElement = document.createElement('option'); // <option> </option>
						var newText = document.createTextNode(subCategory.name); // Action
						newElement.appendChild(newText); // <option>Action</option>
						newElement.setAttribute("value", subCategory.id); // <option value="5">Action</option>
						subCategoryHandle.appendChild(newElement);
					});
				}
			}
			xhr.send();
		}
		// else {
		// 	document.getElementById('productCount').innerHTML = ""
		// }
	}, false);
	// var categoryHandle = document.getElementById('product_category_id');
	// categoryHandle.addEventListener('change', function(){
	// 	if (categoryHandle.value !== "") {
	// 		var xhr = new XMLHttpRequest();
	// 		xhr.open('GET', '/ajax_calls/category_products?category_id=' + categoryHandle.value, true);
	// 		xhr.onreadystatechange = function(){
	// 			if (xhr.readyState === 4 && xhr.status === 200) {
	// 				var result = JSON.parse(xhr.responseText);
	// 				document.getElementById('productCount').innerHTML = "There are " + result.count + " products in DB belonging to " + result.category
	// 			}
	// 		}
	// 		xhr.send();
	// 	}else {
	// 		document.getElementById('productCount').innerHTML = ""
	// 	}
	// }, false);
	// var nameHandle = document.getElementById('product_name');
	// var nameErrorHandle = document.getElementById('nameError');

	// nameHandle.onblur = function(){
	// 	if (nameHandle.value == ""){
	// 		nameErrorHandle.innerHTML = "Can't be blank";
	// 	} else {
	// 		nameErrorHandle.innerHTML = "";
	// 	}
	// };
</script>


app/views/products/show.html.erb
<h2><%= @product.name %></h2>

<p> PRICE : INR <%= @product.price %> </p>
<p> DESCRIPTION : <%= @product.description %> </p>
<p> CATEGORY : <%= link_to @product.category.name, category_path(@product.category.id) %> </p>
<p>SUB_CATEGORY : <%#= @product.sub_category.name %></p>
<p> CODE : <%= @product.code %> </p>
<p> STOCK : <%= @product.stock %> </p>
<p> COD ELIGIBLE : <%= @product.cod_eligible %> </p>

<%= form_for @cart_line_item do |f| %>
   <%= f.label :quantity %>
   <%= f.select :quantity, (1..10).to_a %> <br/>

   <%= f.hidden_field :product_id, value: @product.id %>
   <%= f.submit "Add to cart" %>
<% end %>

<h2>Listing Reviews(<span id="count"><%= @product.reviews.length %></span>)</h2>
<ul id="reviewList">
	<% @product.reviews.each do |review| %>
    
  	 <li><%= review.body %> 
       | <%= review.rating %> 
      </li>
      <% if current_user.id == review.user_id || current_user.is_admin %>
          <%= link_to "destroy", review, method: :delete %>
      <% end %>
	<% end %>
</ul>

<div id="errorMsg"></div>
<%= render '/reviews/form' %>

<%= link_to @product.category.name, category_path(@product.category_id) %>

<%= link_to "List Products", products_path %>

<% if user_signed_in? && current_user.is_admin %>

  <%= link_to "Edit" ,edit_product_path(@product.id) %>

  <%= link_to "Destroy", product_path(@product.id), method: :delete, data: {confirm: "Are You Sure?"} %>
<% end %>
