config/routes.rb
Rails.application.routes.draw do

  resources :vendors
  get 'ajax_calls/find_sub_categories'
  get 'ajax_calls/category_products'
  get 'ajax_calls/check_email_taken'
  get 'dashboard/home'

  get 'dashboard/categories'

  get 'dashboard/products'

  get 'dashboard/users'

  get 'dashboard/reviews'

  get 'dashboard/orders'

  devise_for :users
  resources :products
  get 'home/index'
  get 'home/about'
  get 'home/contact'

  resources :categories
  resources :sub_categories
  resources :cart_line_items
  resources :reviews
  resources :wish_lists
  resources :orders
  resources :addresses
  root 'products#index'

end

app/models/address.rb
class Address < ActiveRecord::Base

	belongs_to :user
	has_many :orders
	belongs_to :cart_line_item
	validates_presence_of :user_id, :street, :pin, :city, :landmark
	validates_numericality_of :user_id, :pin
	validates_length_of :pin, is:6
end

app/models/bank_customer.rb
class BankCustomer < ActiveRecord::Base

	validates_presence_of :name, :acc_no, :balance
	validates_numericality_of :balance, greater_than_or_equal_to: 0
	validates_uniqueness_of :acc_no

	def transaction(amount,code)
		if code == 0 
			# if self.balance - amount < 0 
			# 	puts "Insufficient funds"
			# else
				self.balance = self.balance - amount
				self.update_attributes(balance: self.balance)
			# end
		else
			self.balance += 1
			self.update_attributes(balance: self.balance)
		end
	end
end

app/models/cart_line_item.rb
class CartLineItem < ActiveRecord::Base
	belongs_to :user
	belongs_to :product
	has_many :addresses

	validates_presence_of :user_id, :product_id, :quantity
	validates_numericality_of :user_id, :product_id
	validates_numericality_of :quantity, within:1..10

	# instance method / object method
	def save_or_update
		# binding.pry
		line_item = CartLineItem.find_by(user_id: self.user_id, product_id: self.product_id)
		# binding.pry
		if line_item.nil?
			self.save
			# binding.pry
		else
			line_item.update_attributes(quantity: line_item.quantity + self.quantity)
			# binding.pry
		end
		return true
	end

end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :products
    has_many :sub_categories
	validates_presence_of :name
	validates_uniqueness_of :name
end

app/models/order.rb
class Order < ActiveRecord::Base
	has_many :order_line_items
	belongs_to :user
	belongs_to :address
	validates_presence_of :user_id, :order_number, :order_date

	# callback   # argument (method call)
	after_create :copy_cart_line_items_to_order_line_items
	after_create :empty_cart_line_items
	after_create :calculate_total

	def copy_cart_line_items_to_order_line_items
		user = self.user
		user.cart_line_items.each do |line_item|
			order_line_item = OrderLineItem.new
			order_line_item.product_id = line_item.product_id
			order_line_item.quantity = line_item.quantity
			order_line_item.price = line_item.product.price
			order_line_item.total = order_line_item.quantity * line_item.product.price
			order_line_item.order_id = self.id
			order_line_item.save
		end
	end

	def empty_cart_line_items
		user = self.user
		CartLineItem.delete(user.cart_line_items.pluck(:id))
	end

	def calculate_total
		self.update_attributes(total: self.order_line_items.sum(:total))
	end
end

app/models/order_line_item.rb
class OrderLineItem < ActiveRecord::Base

	belongs_to :order
	belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
    belongs_to :category
    belongs_to :sub_category
    has_one :wish_list
    has_many :reviews
    has_many :cart_line_items
    has_many :order_line_items
	validates_presence_of :name, :price, :category_id, :description
	validates_numericality_of :price, :category_id, greater_than_or_equal_to: 1
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :product
	belongs_to :user

	validates_presence_of :body, :rating
	validates_numericality_of :rating
end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
	belongs_to :category
	has_many :products
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :cart_line_items
	has_many :reviews
	has_many :wish_lists
	has_many :orders
	has_many :addresses
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base

	validates_presence_of :name, :email, :mobile
	validates_uniqueness_of :email, :mobile
end

app/models/wish_list.rb
class WishList < ActiveRecord::Base
	belongs_to :product
	belongs_to :user
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/ajax_calls_helper.rb
module AjaxCallsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ecommerce</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "http://www.gstatic.com/charts/loader.js" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  	<!-- Bootstrap Core CSS -->
    <link href="../../css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="../../css/shop-homepage.css" rel="stylesheet">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/mustache.js/2.3.0/mustache.min.js"/></script>

  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<% if user_signed_in? %>
		  <%= current_user.username %>
		  <%= link_to "Edit Account", edit_user_registration_path %>
		  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
		<% else %>
		  <%= link_to "Login", new_user_session_path %> | <%= link_to "Register", new_user_registration_path %>
		<% end %>

		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>

		<p>
			<%= link_to "Dashboard", dashboard_home_path %>
			<%= link_to "Products", products_path %>
			<%= link_to "Categories", categories_path %>
			<%= link_to "Cart", cart_line_items_path %>
			<%= link_to "WishList", wish_lists_path %>
			<%= link_to "Orders", orders_path %>
			<%= link_to "Address", addresses_path %>
		</p>
		<!-- Bootstrap Core JavaScript -->
	    <script src="../../js/bootstrap.min.js"></script>
		<!-- Navigation -->
	    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	        <div class="container">
	            <!-- Brand and toggle get grouped for better mobile display -->
	            <div class="navbar-header">
	                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	                    <span class="sr-only">Toggle navigation</span>
	                    <span class="icon-bar"></span>
	                    <span class="icon-bar"></span>
	                    <span class="icon-bar"></span>
	                </button>
	                <a class="navbar-brand" href="#">Start Bootstrap</a>
	            </div>
	            <!-- Collect the nav links, forms, and other content for toggling -->
	            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	                <ul class="nav navbar-nav">
	                    <li>
	                        <a href="#">About</a>
	                    </li>
	                    <li>
	                        <a href="#">Services</a>
	                    </li>
	                    <li>
	                        <a href="#">Contact</a>
	                    </li>
	                </ul>
	            </div>
	            <!-- /.navbar-collapse -->
	        </div>
	        <!-- /.container -->
	    </nav>

	    <div class="row">
	    	<div class="col-md-3">
	    		<p class="lead">Shop Name</p>
	    		<div class="list-group">
	    			<% Category.all.each do |category| %>
	    				<%= link_to category.name, category, class: "list-group-item" %>
	    			<% end %>
	    		</div>
	    	</div>
	    	<div class="col-md-9">
	    		<%= yield %>
	    	</div>
	    </div>
	</div>
</body>
</html>

app/views/notification/order_notification.html.erb
<p>Hi <%= @order.user.username %>, <br/>
 Your order has been confirmed </p>

 	<h4><%= @order.order_number %>
 	<%= @order.order_date %>
 	<%= @order.total %> </h4>

 	<ul>
	 	<% @order.order_line_items.each do |line_item| %>
	 		<li> <%= line_item.product.name %> INR <%= line_item.price %> <%= line_item.quantity %> <%= line_item.total %> </li>
	 	<% end %>
    </ul>

<b>Thank you for placing order with us</b>

app/views/notification/order_notification.text.erb
Notification#order_notification

<%= @greeting %>, find me in app/views/notification/order_notification.text.erb

app/views/notification/review_confirmation.html.erb
<p>Hi <%= @review.user.username %>, <br/>
 Your review has been confirmed </p>

 	<ul>
		<li>
			<p> BODY: <%= @review.body %> </p>
			<p> RATING:<%= @review.rating %> </p>
		</li>	
	</ul>
<b>Thank you for placing reviewing the product with us</b>